import "./globals.css";

export const metadata = {
  title: "List-It | Inventory Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` antialiased`}>
        {children}
        </body>
    </html>
  );
}
